# Generated by Django 5.2.8 on 2025-12-29 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EOISubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('property_category', models.CharField(blank=True, max_length=255)),
                ('unit_reference', models.CharField(blank=True, max_length=255)),
                ('approx_size', models.CharField(blank=True, max_length=255)),
                ('applicant_name', models.CharField(max_length=255)),
                ('mobile', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('pan', models.CharField(blank=True, max_length=50)),
                ('address', models.TextField(blank=True)),
                ('offered_rate', models.CharField(max_length=255)),
                ('total_offered_value', models.CharField(max_length=255)),
                ('emd_amount', models.CharField(max_length=255)),
                ('dd_details', models.CharField(blank=True, max_length=255)),
                ('facilitator_name', models.CharField(blank=True, max_length=255)),
                ('facilitator_contact', models.CharField(blank=True, max_length=20)),
                ('agent_name', models.CharField(blank=True, max_length=255)),
                ('agent_rera', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
