# Generated by Django 5.2.8 on 2025-12-29 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eoi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eoisubmission',
            name='address',
        ),
        migrations.RemoveField(
            model_name='eoisubmission',
            name='agent_name',
        ),
        migrations.RemoveField(
            model_name='eoisubmission',
            name='agent_rera',
        ),
        migrations.RemoveField(
            model_name='eoisubmission',
            name='approx_size',
        ),
        migrations.RemoveField(
            model_name='eoisubmission',
            name='dd_details',
        ),
        migrations.RemoveField(
            model_name='eoisubmission',
            name='emd_amount',
        ),
        migrations.RemoveField(
            model_name='eoisubmission',
            name='facilitator_contact',
        ),
        migrations.RemoveField(
            model_name='eoisubmission',
            name='facilitator_name',
        ),
        migrations.RemoveField(
            model_name='eoisubmission',
            name='location',
        ),
        migrations.RemoveField(
            model_name='eoisubmission',
            name='offered_rate',
        ),
        migrations.RemoveField(
            model_name='eoisubmission',
            name='pan',
        ),
        migrations.RemoveField(
            model_name='eoisubmission',
            name='project_name',
        ),
        migrations.RemoveField(
            model_name='eoisubmission',
            name='property_category',
        ),
        migrations.RemoveField(
            model_name='eoisubmission',
            name='total_offered_value',
        ),
        migrations.RemoveField(
            model_name='eoisubmission',
            name='unit_reference',
        ),
    ]
