# Generated by Django 5.2.8 on 2025-11-11 07:24

import django.db.models.deletion
import listings.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('title', models.CharField(blank=True, max_length=500)),
                ('url', models.URLField(blank=True)),
                ('sector', models.CharField(blank=True, max_length=100)),
                ('location', models.TextField(blank=True)),
                ('developer', models.CharField(blank=True, max_length=255)),
                ('rera_no', models.CharField(blank=True, max_length=200)),
                ('rera_link', models.URLField(blank=True)),
                ('tagline', models.TextField(blank=True)),
                ('hero_image_file', models.ImageField(blank=True, null=True, upload_to=listings.models.project_hero_upload_to)),
                ('hero_image_url', models.URLField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('highlights', models.JSONField(blank=True, default=list)),
                ('highlights2', models.JSONField(blank=True, default=list)),
                ('features', models.JSONField(blank=True, default=list)),
                ('summary', models.JSONField(blank=True, default=dict)),
                ('location_info', models.TextField(blank=True)),
                ('developer_info', models.TextField(blank=True)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('external_id', models.CharField(blank=True, help_text='e.g. id used in front-end JSON', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PriceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, max_length=255)),
                ('area', models.CharField(blank=True, max_length=100)),
                ('price', models.CharField(blank=True, max_length=255)),
                ('booking_amount', models.CharField(blank=True, max_length=255)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_list', to='listings.project')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_file', models.ImageField(blank=True, null=True, upload_to=listings.models.project_image_upload_to)),
                ('image_url', models.TextField(blank=True)),
                ('type', models.CharField(choices=[('gallery', 'Gallery'), ('masterplan', 'Master Plan'), ('map', 'Map'), ('network', 'Network'), ('project', 'Project'), ('all', 'All')], default='gallery', max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='listings.project')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
