# Generated by Django 5.2.8 on 2025-12-01 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-is_prioritized', '-created_at']},
        ),
        migrations.AddField(
            model_name='project',
            name='is_prioritized',
            field=models.BooleanField(default=False, help_text='Tick to feature this project prominently on the frontend.'),
        ),
        migrations.AddField(
            model_name='project',
            name='view_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of times this project page was viewed.'),
        ),
    ]
