# Generated by Django 5.2.8 on 2026-04-13 14:53

import django.db.models.deletion
import listings.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_alter_project_options_project_is_prioritized_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Developer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, help_text="SEO-friendly URL key, e.g. 'dlf-limited'", max_length=255, unique=True)),
                ('logo_file', models.ImageField(blank=True, null=True, upload_to=listings.models.developer_logo_upload_to)),
                ('logo_url', models.URLField(blank=True, help_text='External logo URL (fallback)')),
                ('tagline', models.CharField(blank=True, max_length=500)),
                ('description', models.TextField(blank=True)),
                ('established_year', models.PositiveSmallIntegerField(blank=True, help_text='Year developer was founded', null=True)),
                ('headquarters', models.CharField(blank=True, max_length=255)),
                ('website', models.URLField(blank=True)),
                ('rera_developer_id', models.CharField(blank=True, help_text='RERA developer registration number', max_length=200)),
                ('is_featured', models.BooleanField(default=False, help_text='Feature this developer prominently on the frontend')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-is_featured', 'name'],
            },
        ),
        migrations.AlterField(
            model_name='project',
            name='developer',
            field=models.CharField(blank=True, help_text='Legacy text field — kept for backward compatibility', max_length=255),
        ),
        migrations.AddField(
            model_name='project',
            name='developer_obj',
            field=models.ForeignKey(blank=True, help_text='Select from registered developers (preferred over text field)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='listings.developer'),
        ),
    ]
