# Generated by Django 5.2.8 on 2026-04-13 16:38

import listings.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_developer_alter_project_developer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='developer',
            name='logo_file',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to=listings.models.developer_logo_upload_to),
        ),
        migrations.AlterField(
            model_name='project',
            name='hero_image_file',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to=listings.models.project_hero_upload_to),
        ),
        migrations.AlterField(
            model_name='projectimage',
            name='image_file',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to=listings.models.project_image_upload_to),
        ),
    ]
