# Generated by Django 5.2.8 on 2026-04-16 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_alter_developer_logo_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='developer',
            name='acquisition_method',
            field=models.JSONField(blank=True, default=list, help_text="List of dicts: [{'title': '...', 'desc': '...'}]"),
        ),
        migrations.AddField(
            model_name='developer',
            name='faqs',
            field=models.JSONField(blank=True, default=list, help_text="List of dicts: [{'question': '...', 'answer': '...'}]"),
        ),
        migrations.AddField(
            model_name='developer',
            name='stats',
            field=models.JSONField(blank=True, default=dict, help_text='Metrics e.g. years_of_experience, area_delivered, completed_projects'),
        ),
        migrations.AddField(
            model_name='developer',
            name='testimonials',
            field=models.JSONField(blank=True, default=list, help_text="List of dicts: [{'client': '...', 'feedback': '...', 'rating': 5}]"),
        ),
        migrations.AddField(
            model_name='project',
            name='completion_date',
            field=models.CharField(blank=True, help_text='e.g. Dec 2025', max_length=100),
        ),
        migrations.AddField(
            model_name='project',
            name='project_area',
            field=models.CharField(blank=True, help_text='e.g. 5 Acres', max_length=100),
        ),
        migrations.AddField(
            model_name='project',
            name='property_type',
            field=models.CharField(blank=True, choices=[('residential', 'Residential'), ('commercial', 'Commercial'), ('sco', 'SCO Plots'), ('plots', 'Residential Plots')], max_length=50),
        ),
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(blank=True, choices=[('under_construction', 'Under Construction'), ('ready_to_move', 'Ready to Move In'), ('delivered', 'Delivered')], max_length=50),
        ),
        migrations.AddField(
            model_name='project',
            name='total_units',
            field=models.CharField(blank=True, help_text='e.g. 500 Units', max_length=100),
        ),
        migrations.AddField(
            model_name='project',
            name='towers',
            field=models.CharField(blank=True, help_text='e.g. 4 Towers', max_length=50),
        ),
    ]
