# Generated by Django 5.2.8 on 2026-04-14 12:39

import blogs.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('slug', models.SlugField(blank=True, help_text='Auto-generated from title. SEO-friendly URL key.', max_length=320, unique=True)),
                ('excerpt', models.TextField(blank=True, help_text='Short summary (used as meta description, ~150-160 chars ideal).', max_length=400)),
                ('content', models.TextField(help_text='Full article body in HTML. Use proper H2/H3 heading hierarchy.')),
                ('category', models.CharField(choices=[('market-insights', 'Market Insights'), ('buying-guide', 'Buying Guide'), ('investment-tips', 'Investment Tips'), ('location-guide', 'Location Guide'), ('developer-news', 'Developer News')], db_index=True, default='market-insights', max_length=50)),
                ('tags', models.JSONField(blank=True, default=list, help_text="List of keyword tags, e.g. ['SCO plots', 'Gurgaon']")),
                ('cover_image_file', models.ImageField(blank=True, help_text='Upload a cover image (1200×630 px recommended for OG).', max_length=500, null=True, upload_to=blogs.models.blog_cover_upload_to)),
                ('cover_image_url', models.URLField(blank=True, help_text='External cover image URL (fallback if no file uploaded).')),
                ('cover_image_alt', models.CharField(blank=True, help_text='Alt text for cover image (important for accessibility & SEO).', max_length=300)),
                ('author_name', models.CharField(default='Zip Realtors LLP', max_length=200)),
                ('author_title', models.CharField(blank=True, default='Real Estate Expert, Gurgaon', max_length=200)),
                ('author_avatar_url', models.URLField(blank=True)),
                ('meta_title', models.CharField(blank=True, help_text='SEO title tag override (leave blank to use article title). Max 60 chars recommended.', max_length=120)),
                ('meta_description', models.CharField(blank=True, help_text='Meta description override (leave blank to use excerpt). Max 160 chars recommended.', max_length=320)),
                ('focus_keyword', models.CharField(blank=True, help_text="Primary SEO keyword this article targets, e.g. 'SCO plots Gurgaon 2025'.", max_length=200)),
                ('canonical_url', models.URLField(blank=True, help_text='Canonical URL override (leave blank for auto-canonical).')),
                ('is_published', models.BooleanField(default=False, help_text='Tick to make this post publicly visible via the API.')),
                ('is_featured', models.BooleanField(default=False, help_text='Feature this post prominently on the blog listing page.')),
                ('published_at', models.DateTimeField(blank=True, help_text='Set automatically when first published. Can be overridden.', null=True)),
                ('read_time_minutes', models.PositiveSmallIntegerField(default=0, help_text='Estimated reading time — auto-computed from word count on save.')),
                ('view_count', models.PositiveIntegerField(default=0, help_text='Number of times this post detail page was fetched.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Blog Post',
                'verbose_name_plural': 'Blog Posts',
                'ordering': ['-is_featured', '-published_at', '-created_at'],
            },
        ),
    ]
