# Generated by Django 5.2.8 on 2026-04-15 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enquiries', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enquiry',
            name='sf_error',
        ),
        migrations.RemoveField(
            model_name='enquiry',
            name='sf_response',
        ),
        migrations.RemoveField(
            model_name='enquiry',
            name='sf_success',
        ),
    ]
